### ISSUE TITLE
Character sheet fails to render sometimes in  sidebar

### ISSUE THREAD

**Issue by zkat** [cwegrzyn/iron-vault#129]
It seems kind of random, but the contents of embeds and blocks isn't quite rendering.

Idk what's really going on but it probably has to do with trying to render before indexing is complete

**Comment by zkat** [comment]
I wonder if I need to use this class instead: https://docs.obsidian.md/Reference/TypeScript+API/MarkdownPreviewView

**Comment by cwegrzyn** [comment]
Seems to have been resolved by #136 ! Have tested with opening/closing vault, force reload of the window, and hot reload of plugin.
