### ISSUE TITLE
Render oracle links in oracle reference modal

### ISSUE THREAD

**Issue by cwegrzyn** [cwegrzyn/iron-vault#148]
In the oracle reference modal, when other oracles are referenced with `[name](id:oracle/id)` we should render them as links. (e.g., Starforged's _Background Assets_ oracle)

**Comment by zkat** [comment]
This is fixed now. There's a _separate_ bug where oracle links don't seem to be working anymore, but I'll look into that separately.

**Comment by zkat** [comment]
nevermind, oracles are working fine. The bug was with assets, and that's also fixed now.
