### ISSUE TITLE
NPC note generation command

### ISSUE THREAD

**Issue by zkat** [cwegrzyn/iron-vault#83]
Basic NPC note generation command that creates a note with the NPC's name, and frontmatter fields for connection and bond status.

**Comment by zkat** [comment]
1. This is really what this issue was about: we should pretty much just generate the name (because note name), and then connection/note status. I think everything else can be left up to the user to template however they want.
2. See above, I'd really rather not do this, to give people freedom in how they organize their NPC docs
3. I really don't want to depend on external plugins :\
4. This might be a Future Feature we can do in the context of "we'll fill in the fields using oracles", which is cool, but way more than we need any time soon.

**Comment by cwegrzyn** [comment]
Plan here: convert "generate an entity" to (a) rendering as an oracle group node in the journal and (b) add an option to generate a note with a table to the modal
